group: stable
dist: xenial
os: linux
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
before_install:
- sudo apt-get -qq update
install: pip install -r requirements.txt
before_script:
    - pip install flake8 twistedchecker  # pytest  # add another testing frameworks later
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E1,E2,E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    # ignore E3xx errors, Twisted has different empty line convention
    - flake8 . --count --ignore=E3 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - twistedchecker --pep8=y -d W9001,W9002 cowrie twisted.plugins
#   Twistedchecker has some version issues, disable for now
script: PYTHONPATH=${TRAVIS_BUILD_DIR} trial cowrie
notifications:
  email: false
  slack:
    secure: DiFWUr5A+YPJ5vGbjLCHRdp+TM6dDI7/b3JuyE+bBdV4BVpQsYx2XhH1nVdDXYTf2jaT0jjYnRQuQKTHXJWSrBlklozdVf+WOJmlFFZ3WZmyn6EgwfqE9fuz9vZcD1Yt1M1Fxu14Ffj1iWxiQ+VATxsYtowcOMgAESyYS31qhcMS48jvf/V1TCBh/Bi5nk+xkoZ3ThMg8w+sXSzUp17IP/T8uWUl28Y401lk4diV7GFVNJx66IT6u0CY0i0dOV69qPggHUn43NigIh9zv0QhjE2WLVcVUSDsDte+xVrEyvovJ+xdy08x/X9pa2d/tDycZz2nBEktIZLSxF65p7jBlytCLVwW8lhgRgZZSd142S0FvpRx8vap4CbtgLs7ltzJF3X1Ca0LsUe5vDgoJPd5eYCNCxowJldT8eWqIzmWwo2/PXOsAM5FJg5l7QIWH6gSEaauC/8Nn74or+wpLJsP5j1GqIGwDCRv3qclv/KHJWb8azPoov8csf4ulI270I5ihXeA8+rEZWekpgY2RHfcTwFgllxA1AnBqLsaCECkatYauLHyblYdOSbQJYB2a3ZwWoNoQ5WBt/FSzFxuYJPySPwXyRnXlBCxt0xMK+qTCA3k5RwPG5gbre1tgZPbxMn23AkRLBsITPYdEPZMfz6dRavWr8ZObfbXeblAf3xtBss=
matrix:
  allow_failures:
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
